const API_ROUTES = {
  ROOT_URL: process.env.NEXT_PUBLIC_API_ROOT_URL,
  AUTHORIZE_PATH: process.env.NEXT_PUBLIC_API_AUTHORIZE_PATH,
  REFRESH_TOKEN_PATH: process.env.NEXT_PUBLIC_API_TOKEN_REFRESH_PATH,
};

export default API_ROUTES;
